# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        PR\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        main:
          id: fos_user.user_provider.username


    firewalls:
        main_login:
          pattern:  ^/login$
          anonymous: true
          logout_on_user_change: true

        main:
          pattern:      ^/
          anonymous:    true
          provider:     main
          form_login:
            login_path: fos_user_security_login
            check_path: fos_user_security_check
          logout:
            path:       fos_user_security_logout
            target:     accueil
          remember_me:
            secret:    "%secret%"
          logout_on_user_change: true


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
