admin:
    path: /
    defaults: { _controller: PRAdminBundle:Admin:index }

admin_accueil:
    path: /accueil
    defaults: { _controller: PRAdminBundle:Accueil:accueil }

admin_accueil_edit:
    path: /accueil/modifier
    defaults: { _controller: PRAdminBundle:Accueil:accueilValidate }

admin_article:
    path: /articles
    defaults: { _controller: PRAdminBundle:Articles:article }

admin_article_new:
    path: /articles/new
    defaults: { _controller: PRAdminBundle:Articles:articleNew }

admin_article_edit:
    path: /articles/edit/{id}
    defaults: { _controller: PRAdminBundle:Articles:articleEdit }

admin_article_delete:
    path: /articles/delete/{id}
    defaults: { _controller: PRAdminBundle:Articles:articleDelete }

admin_article_publish:
    path: /articles/publish/{id}
    defaults: { _controller: PRAdminBundle:Articles:articlePublish }

admin_gallery:
    path: /galeries
    defaults: { _controller: PRAdminBundle:Gallery:gallery }

admin_contact:
    path: /contacts
    defaults: { _controller: PRAdminBundle:Contacts:contact }
