admin:
    path: /
    defaults: { _controller: PRAdminBundle:Admin:index }

admin_accueil:
    path: /accueil
    defaults: { _controller: PRAdminBundle:Accueil:accueil }

admin_accueil_edit:
    path: /accueil/modifier
    defaults: { _controller: PRAdminBundle:Accueil:accueilValidate }

admin_article:
    path: /articles
    defaults: { _controller: PRAdminBundle:Articles:article }

admin_article_new:
    path: /articles/new
    defaults: { _controller: PRAdminBundle:Articles:articleNew }

admin_article_edit:
    path: /articles/edit/{id}
    defaults: { _controller: PRAdminBundle:Articles:articleEdit }

admin_article_delete:
    path: /articles/delete/{id}
    defaults: { _controller: PRAdminBundle:Articles:articleDelete }

admin_article_publish:
    path: /articles/publish/{id}
    defaults: { _controller: PRAdminBundle:Articles:articlePublish }

admin_prestations:
    path: /prestations
    defaults: { _controller: PRAdminBundle:Prestations:prestation }

admin_prestations_new:
    path: /prestations/new
    defaults: { _controller: PRAdminBundle:Prestations:prestationNew }

admin_prestations_edit:
    path: /prestations/edit/{id}
    defaults: { _controller: PRAdminBundle:Prestations:prestationEdit }

admin_prestations_delete:
    path: /prestations/delete/{id}
    defaults: { _controller: PRAdminBundle:Prestations:prestationDelete }

admin_gallery:
    path: /galeries
    defaults: { _controller: PRAdminBundle:Gallery:gallery }

admin_gallery_new:
    path: /galeries/new
    defaults: { _controller: PRAdminBundle:Gallery:galleryNew }

admin_gallery_edit:
    path: /galeries/edit/{gallery}
    defaults: { _controller: PRAdminBundle:Gallery:galleryEdit }

admin_gallery_delete:
    path: /galeries/delete/{id}
    defaults: { _controller: PRAdminBundle:Gallery:galleryDelete }

admin_image_del:
    path: /galeries/delImg/{image}/{galleryName}
    defaults: { _controller: PRAdminBundle:Gallery:deleteImageFromGallery }

admin_contact:
    path: /contacts
    defaults: { _controller: PRAdminBundle:Contacts:contact }

admin_contact_new:
    path: /contacts/new
    defaults: { _controller: PRAdminBundle:Contacts:contactNew }

admin_contact_edit:
    path: /contacts/edit/{id}
    defaults: { _controller: PRAdminBundle:Contacts:contactEdit }

admin_contact_delete:
    path: /contacts/delete/{id}
    defaults: { _controller: PRAdminBundle:Contacts:contactDelete }
