accueil:
    path: /
    defaults: { _controller: PRVitrineBundle:Vitrine:index }

actualites:
    path: /actu
    defaults: { _controller: PRVitrineBundle:Actualities:actualites }

prestations:
    path: /prestations
    defaults: { _controller: PRVitrineBundle:Business:prestations }

galleries:
    path: /galleries
    defaults: { _controller: PRVitrineBundle:Gallery:galleries }

gallery_show:
    path: /gallery_show/{gallery}
    defaults: { _controller: PRVitrineBundle:Gallery:galleryDetail }

reportages:
    path: /reportages
    defaults: { _controller: PRVitrineBundle:Gallery:reportages }

contacts:
    path: /contacts
    defaults: { _controller: PRVitrineBundle:Contact:contacts }

gestion_contact:
    path: /contacts_mail
    defaults: { _controller: PRVitrineBundle:Contact:contactsEnvoi }

mentions_legales:
    path: /mentions_legales
    defaults: { _controller: PRVitrineBundle:Contact:mentionsLegales}
