accueil:
    path: /
    defaults: { _controller: PRVitrineBundle:Vitrine:index }

gallerie:
    path: /gallerie
    defaults: { _controller: PRVitrineBundle:Vitrine:gallerie }

contacts:
    path: /contacts
    defaults: { _controller: PRVitrineBundle:Vitrine:contacts }

upload:
    path: /upload
    defaults: { _controller: PRVitrineBundle:Vitrine:upload }

carousel:
    path: /carousel
    defaults: { _controller: PRVitrineBundle:Vitrine:carousel }
