accueil:
    path: /
    defaults: { _controller: PRVitrineBundle:Vitrine:index }

actualites:
    path: /actu
    defaults: { _controller: PRVitrineBundle:Vitrine:actualites }

prestations:
    path: /prestations
    defaults: { _controller: PRVitrineBundle:Vitrine:prestations }

galleries:
    path: /galleries
    defaults: { _controller: PRVitrineBundle:Vitrine:galleries }

gallery_show:
    path: /gallery_show/{gallery}
    defaults: { _controller: PRVitrineBundle:Vitrine:galleryDetail }

reportages:
    path: /reportages
    defaults: { _controller: PRVitrineBundle:Vitrine:reportages }

contacts:
    path: /contacts
    defaults: { _controller: PRVitrineBundle:Vitrine:contacts }
