<?php

namespace PR\VitrineBundle\Repository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{

    public function getMaxOrder($path){
        $query = $this->createQueryBuilder('i');
        $query->select('i, MAX(i.pictureOrder) AS max_order')
              ->where('i.galleryPath=:path')
              ->setParameter('path',$path);
            

        return $query->getQuery()->getResult();
    }
}
