<?php

namespace PR\AdminBundle\Repository;

/**
 * MenuAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuAdminRepository extends \Doctrine\ORM\EntityRepository
{
}
